MODEL:
  NAME: 'resnet50' # 'resnet50' 'seresnet50' 'densenet169'
  PRETRAIN_PATH: 'your_path/.torch/models/resnet50-19c8e357.pth' # pretrained resnest50 model; change it to your path
  # PRETRAIN_PATH_SE: '/home/cgy/.torch/models/seresnet50-60a8950a85b2b.pkl'
  # PRETRAIN_PATH_DENSE: '/home/cgy/.torch/models/densenet169-b2777c0a.pth'
  CAL: True


INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('msmt17') #dukemtmc market1501 msmt17

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 160
  BASE_LR: 0.0002
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BIAS: 0.001
  SMOOTH: 0.1
  IMS_PER_BATCH: 80

  STEPS: [40, 80, 120]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 100
  EVAL_PERIOD: 10


TEST:
  IMS_PER_BATCH: 512
  RE_RANK: False
  WEIGHT: "path"

OUTPUT_DIR: "your_path/checkpoint/name_to_save"
